In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import math

In [2]:
df = pd.read_csv("Trace_TRAIN.csv", header = None)

In [3]:
type(df.columns[0])

numpy.int64

In [4]:
df.iloc[0]

0      1.000000
1      0.544070
2      0.657863
3      0.611239
4      0.545413
         ...
271    0.554263
272    0.514147
273    0.603773
274    0.596331
275    0.583224
Name: 0, Length: 276, dtype: float64

In [5]:
df_1 = df.sort_values(by = [0])

In [6]:
df_1

,0,1,2,3,4,5,6,7,8,9,...,266,267,268,269,270,271,272,273,274,275
0,1,0.544070,0.657863,0.611239,0.545413,0.532156,0.593013,0.595280,0.538277,0.563429,...,0.588226,0.577886,0.598069,0.583695,0.602877,0.554263,0.514147,0.603773,0.596331,0.583224
35,1,0.578414,0.564529,0.621712,0.615501,0.568938,0.590108,0.611278,0.606414,0.662229,...,0.618024,0.582313,0.615947,0.514177,0.565427,0.608845,0.619287,0.616195,0.574924,0.595827
39,1,0.610521,0.621260,0.694262,0.546820,0.579827,0.576833,0.623971,0.549951,0.589048,...,0.619005,0.620541,0.591554,0.593210,0.636987,0.558369,0.593279,0.604549,0.636853,0.622172
45,1,0.502552,0.598754,0.603983,0.544759,0.645436,0.607110,0.584153,0.626348,0.556643,...,0.561244,0.554111,0.543664,0.565976,0.613606,0.599514,0.484127,0.573103,0.589664,0.549785
98,1,0.674236,0.699501,0.724766,0.736954,0.678820,0.667963,0.666761,0.629702,0.618875,...,0.631834,0.630219,0.643520,0.604948,0.612756,0.605087,0.594663,0.680926,0.612721,0.650197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,4,-1.904420,-1.927255,-1.890280,-1.900769,-1.897393,-1.928063,-1.916945,-1.954691,-1.914794,...,0.619676,0.540935,0.572456,0.602884,0.594657,0.592506,0.543837,0.529457,0.609561,0.586370
46,4,-1.665489,-1.647157,-1.587652,-1.653690,-1.611148,-1.598953,-1.625933,-1.622408,-1.602705,...,0.678327,0.647362,0.684946,0.645228,0.687207,0.698321,0.644367,0.700318,0.623251,0.652755
75,4,-1.499155,-1.479791,-1.440565,-1.473746,-1.518472,-1.523205,-1.461763,-1.507300,-1.486842,...,0.746073,0.739075,0.740359,0.690094,0.728535,0.723025,0.728732,0.706519,0.724346,0.710523
21,4,-1.528701,-1.489130,-1.494410,-1.524356,-1.498376,-1.447686,-1.546160,-1.545736,-1.482808,...,0.746798,0.703390,0.719697,0.730584,0.733897,0.709781,0.736965,0.758608,0.684470,0.703240
69,4,-2.020488,-2.038183,-2.031425,-2.088887,-2.037234,-2.056556,-2.146249,-2.078076,-2.062645,...,0.547296,0.543265,0.523343,0.516688,0.510032,0.515707,0.530190,0.580528,0.558666,0.574958

In [7]:
df_2 = df_1.drop([0], axis=1)

In [8]:
df_3 = df_2.reset_index(drop=True)
df = df_3
df

,1,2,3,4,5,6,7,8,9,10,...,266,267,268,269,270,271,272,273,274,275
0,0.544070,0.657863,0.611239,0.545413,0.532156,0.593013,0.595280,0.538277,0.563429,0.595956,...,0.588226,0.577886,0.598069,0.583695,0.602877,0.554263,0.514147,0.603773,0.596331,0.583224
1,0.578414,0.564529,0.621712,0.615501,0.568938,0.590108,0.611278,0.606414,0.662229,0.638254,...,0.618024,0.582313,0.615947,0.514177,0.565427,0.608845,0.619287,0.616195,0.574924,0.595827
2,0.610521,0.621260,0.694262,0.546820,0.579827,0.576833,0.623971,0.549951,0.589048,0.632450,...,0.619005,0.620541,0.591554,0.593210,0.636987,0.558369,0.593279,0.604549,0.636853,0.622172
3,0.502552,0.598754,0.603983,0.544759,0.645436,0.607110,0.584153,0.626348,0.556643,0.552215,...,0.561244,0.554111,0.543664,0.565976,0.613606,0.599514,0.484127,0.573103,0.589664,0.549785
4,0.674236,0.699501,0.724766,0.736954,0.678820,0.667963,0.666761,0.629702,0.618875,0.671192,...,0.631834,0.630219,0.643520,0.604948,0.612756,0.605087,0.594663,0.680926,0.612721,0.650197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,-1.904420,-1.927255,-1.890280,-1.900769,-1.897393,-1.928063,-1.916945,-1.954691,-1.914794,-1.896685,...,0.619676,0.540935,0.572456,0.602884,0.594657,0.592506,0.543837,0.529457,0.609561,0.586370
96,-1.665489,-1.647157,-1.587652,-1.653690,-1.611148,-1.598953,-1.625933,-1.622408,-1.602705,-1.602250,...,0.678327,0.647362,0.684946,0.645228,0.687207,0.698321,0.644367,0.700318,0.623251,0.652755
97,-1.499155,-1.479791,-1.440565,-1.473746,-1.518472,-1.523205,-1.461763,-1.507300,-1.486842,-1.472481,...,0.746073,0.739075,0.740359,0.690094,0.728535,0.723025,0.728732,0.706519,0.724346,0.710523
98,-1.528701,-1.489130,-1.494410,-1.524356,-1.498376,-1.447686,-1.546160,-1.545736,-1.482808,-1.500363,...,0.746798,0.703390,0.719697,0.730584,0.733897,0.709781,0.736965,0.758608,0.684470,0.703240
99,-2.020488,-2.038183,-2.031425,-2.088887,-2.037234,-2.056556,-2.146249,-2.078076,-2.062645,-2.040551,...,0.547296,0.543265,0.523343,0.516688,0.510032,0.515707,0.530190,0.580528,0.558666,0.574958

In [9]:
df

,1,2,3,4,5,6,7,8,9,10,...,266,267,268,269,270,271,272,273,274,275
0,0.544070,0.657863,0.611239,0.545413,0.532156,0.593013,0.595280,0.538277,0.563429,0.595956,...,0.588226,0.577886,0.598069,0.583695,0.602877,0.554263,0.514147,0.603773,0.596331,0.583224
1,0.578414,0.564529,0.621712,0.615501,0.568938,0.590108,0.611278,0.606414,0.662229,0.638254,...,0.618024,0.582313,0.615947,0.514177,0.565427,0.608845,0.619287,0.616195,0.574924,0.595827
2,0.610521,0.621260,0.694262,0.546820,0.579827,0.576833,0.623971,0.549951,0.589048,0.632450,...,0.619005,0.620541,0.591554,0.593210,0.636987,0.558369,0.593279,0.604549,0.636853,0.622172
3,0.502552,0.598754,0.603983,0.544759,0.645436,0.607110,0.584153,0.626348,0.556643,0.552215,...,0.561244,0.554111,0.543664,0.565976,0.613606,0.599514,0.484127,0.573103,0.589664,0.549785
4,0.674236,0.699501,0.724766,0.736954,0.678820,0.667963,0.666761,0.629702,0.618875,0.671192,...,0.631834,0.630219,0.643520,0.604948,0.612756,0.605087,0.594663,0.680926,0.612721,0.650197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,-1.904420,-1.927255,-1.890280,-1.900769,-1.897393,-1.928063,-1.916945,-1.954691,-1.914794,-1.896685,...,0.619676,0.540935,0.572456,0.602884,0.594657,0.592506,0.543837,0.529457,0.609561,0.586370
96,-1.665489,-1.647157,-1.587652,-1.653690,-1.611148,-1.598953,-1.625933,-1.622408,-1.602705,-1.602250,...,0.678327,0.647362,0.684946,0.645228,0.687207,0.698321,0.644367,0.700318,0.623251,0.652755
97,-1.499155,-1.479791,-1.440565,-1.473746,-1.518472,-1.523205,-1.461763,-1.507300,-1.486842,-1.472481,...,0.746073,0.739075,0.740359,0.690094,0.728535,0.723025,0.728732,0.706519,0.724346,0.710523
98,-1.528701,-1.489130,-1.494410,-1.524356,-1.498376,-1.447686,-1.546160,-1.545736,-1.482808,-1.500363,...,0.746798,0.703390,0.719697,0.730584,0.733897,0.709781,0.736965,0.758608,0.684470,0.703240
99,-2.020488,-2.038183,-2.031425,-2.088887,-2.037234,-2.056556,-2.146249,-2.078076,-2.062645,-2.040551,...,0.547296,0.543265,0.523343,0.516688,0.510032,0.515707,0.530190,0.580528,0.558666,0.574958

In [10]:
X = df.to_numpy(dtype = None, copy = False)

In [11]:
X

array([[ 0.54407042,  0.65786304,  0.61123908, ...,  0.60377304,
         0.59633124,  0.58322427],
       [ 0.57841358,  0.56452867,  0.62171229, ...,  0.61619496,
         0.57492435,  0.595827  ],
       [ 0.61052054,  0.62125976,  0.69426228, ...,  0.60454922,
         0.63685297,  0.62217219],
       ...,
       [-1.4991548 , -1.4797911 , -1.4405654 , ...,  0.70651888,
         0.72434568,  0.71052337],
       [-1.5287005 , -1.4891303 , -1.4944099 , ...,  0.75860841,
         0.68447013,  0.70323965],
       [-2.0204875 , -2.0381827 , -2.0314246 , ...,  0.5805277 ,
         0.5586662 ,  0.57495754]])

In [12]:
len(X)

100

In [13]:
len(X[0])

275

In [14]:
def calculate_dist_mat(X):
    dist_mat= np.zeros((len(X),len(X)))
    for i in range(1, len(dist_mat[0])):
        for j in range(i):
            for k in range(len(dist_mat[0])):
                if k == i or k == j:
                    continue
                dist_mat[i][j] += abs(np.linalg.norm(X[i] - X[k]) - np.linalg.norm(X[j] - X[k]))
            dist_mat[i][j] /= (len(dist_mat[0])-2)
    return dist_mat

In [15]:
def calculate_Madd(X,i,j):
    madd = 0.0
    for k in range(len(X)):
        if k == i or k == j:
            continue
        madd += abs(np.linalg.norm(X[i] - X[k]) - np.linalg.norm(X[j] - X[k]))
    madd /= (len(X) - 2)
    return madd

In [16]:
def ret_min(a, b): # Returns minimum of a and b
  if a>b:
    return b

  return a

In [17]:
from collections.abc import Iterable

def flatten(lis):
     for item in lis:
         if isinstance(item, Iterable) and not isinstance(item, str):
             for x in flatten(item):
                 yield x
         else:        
             yield item

In [18]:
def within_cluster_distance(X,hierarchy):
  w = []  
  for i in range(len(hierarchy)):
    s1 = 0
    cluster = sorted(list(flatten(hierarchy[i])))
    if len(cluster) == 1:
        w += [0]
        continue
            
    else:
      for j in range(len(cluster)-1):
        for k in range(j+1,len(cluster)):
           s1 += calculate_Madd(X,cluster[j],cluster[k])
      s1 /= (len(cluster)*(len(cluster)-1))/2
      w += [s1]
    
  return w

In [19]:
def between_cluster_distance(X,b,hierarchy):
  
  b_min = float("inf")
  for i in range(len(hierarchy)-1):
    cluster_1 = sorted(list(flatten(hierarchy[i])))
    for j in range(i+1,len(hierarchy)):
      s2 = 0.0
      cluster_2 = sorted(list(flatten(hierarchy[j])))
      for k in range(len(cluster_1)):
        for l in range(len(cluster_2)):
          s2 += calculate_Madd(X,cluster_1[k], cluster_2[l])
      s2 /= (len(cluster_1) * len(cluster_2))
      b[i][j] = s2
      
           
  return b

In [20]:
def calculate_between_cluster_distance(b,min_i,min_j,n1,n2):
    for i in range(len(b)):
        if i<min_i:
            b[i][min_i] = (n1*b[i][min_i]+n2*b[i][min_j])/(n1+n2)
        elif i>min_j:
            b[min_i][i] = (n1*b[min_i][i]+n2*b[min_j][i])/(n1+n2)
    
    b = np.delete(b, (min_j), axis=0) # Deleting  min_j row
    b = np.delete(b, (min_j), axis=1) # Deleting  min_j column
    return b

In [21]:
def within_max(w):
    max = w[0]
    for i in range(1,len(w)):
        if w[i] >= max:
            max = w[i]
            
    return max

In [22]:
def between_min(b):
    min = b[0][1]
    for i in range(len(b[0])):
        for j in range(i+1,len(b[0])):
            if b[i][j] <= min :
                min = b[i][j]
    return min

In [23]:
def clustering(X,matrix, hierarchy,d,k_max,w,b):
  
  # Base case
  if len(matrix) == 2:
    min_i = 0
    min_j = 1
    n1 = len(list(flatten(hierarchy[min_i])))
    n2 = len(list(flatten(hierarchy[min_j])))
    hierarchy = hierarchy[:min_i] + [[hierarchy[min_i], hierarchy[min_j]]] + hierarchy[min_j+1:]
    B = d[-1]
    d = d[:-1]
    w = (n1*(n1-1)*w[min_i]+n2*(n2-1)*w[min_j]+2*n1*n2*b[min_i][min_j])/((n1+n2)*(n1+n2-1))
    d += [(B/w) - 0.015 * len(hierarchy) * math.log(100,10)]

    max = d[0]
    index = 0
    for i in range(1,len(d)):
        if d[i] > max:
            max = d[i]
            index = i
    return k_max-index
    




  min = matrix[1][0] #initializing minimum distance
  min_i, min_j = 1, 0

  for i in range(1, len(matrix[0])):
    for j in range(i):
      if i>j and ((i-j) == 1):
        if matrix[i][j]<min:
          min = matrix[i][j]
          min_i = i
          min_j = j

  # Swapping min_i, min_j in order to maintain min_i < min_j
  if min_i > min_j:
    a = min_i
    min_i = min_j
    min_j = a
  
  n1 = len(list(flatten(hierarchy[min_i])))
  n2 = len(list(flatten(hierarchy[min_j])))

  hierarchy = hierarchy[:min_i] + [[hierarchy[min_i], hierarchy[min_j]]] + hierarchy[min_j+1:]

  dist_mat = np.copy(matrix) # Copying the original matrix so that original matrix is not affected by further operations
  dist_mat = np.delete(dist_mat, (min_j), axis=0) # Deleting  min_j row
  dist_mat = np.delete(dist_mat, (min_j), axis=1) # Deleting  min_j column

  dist_min_i = [] # List of distances from point min_i to all other points except min_j
  dist_min_j = [] # List of distances from point min_j to all other points except min_i

  for i in range(len(matrix)):
    if i<min_i:
      dist_min_i += [matrix[min_i][i]]
      dist_min_j += [matrix[min_j][i]]
    elif i == min_i or i == min_j:
      continue
    elif i<min_j:
      dist_min_i += [matrix[i][min_i]]
      dist_min_j += [matrix[min_j][i]]
    else:
      dist_min_i += [matrix[i][min_i]]
      dist_min_j += [matrix[i][min_j]]
  
  # Filling the min_i  row of new distance matrix
  for i in range(len(dist_min_i)):
    if i < min_i:
      dist_mat[min_i][i] = ret_min(dist_min_i[i], dist_min_j[i])
    else:
      dist_mat[i+1][min_i] = ret_min(dist_min_i[i], dist_min_j[i])
  
  dist_min_i = []
  dist_min_j = []
  
  
  
 
  l_h = len(hierarchy)
  if (l_h <= k_max and l_h > 1):
    if(l_h == k_max):
        #b_min = between_cluster_distance(hierarchy,X)
        w = within_cluster_distance(X,hierarchy)
        b = between_cluster_distance(X,b,hierarchy)
        w_max = within_max(w)
        b_min = between_min(b)
        d += [(b_min/w_max) - 0.015 * l_h * math.log(100,10)]
    else:
        w[min_i] = (n1*(n1-1)*w[min_i]+n2*(n2-1)*w[min_j]+2*n1*n2*b[min_i][min_j])/((n1+n2)*(n1+n2-1))
        w = w[:min_j]+w[min_j+1:]
        b = calculate_between_cluster_distance(b,min_i,min_j,n1,n2)
        w_max = within_max(w)
        b_min = between_min(b)
        d += [(b_min/w_max)- 0.015 * l_h * math.log(100,10)]
        if(l_h == 2):
            d += [b_min]

  opt_max = clustering(X,dist_mat, hierarchy,d,k_max,w,b) # The recusion call

  return opt_max

In [24]:
opt_cluster = []
dist_mat = calculate_dist_mat(X)
k_max = 20
b = np.zeros((k_max,k_max))
hier1 = [[i] for i in range(len(dist_mat))]
opt_cluster += [clustering(X,dist_mat, hier1,[],20,[],b)]

In [25]:
opt_cluster

[2]

In [26]:
df = pd.read_csv("Trace_TRAIN.csv", header = None)

In [27]:
df

,0,1,2,3,4,5,6,7,8,9,...,266,267,268,269,270,271,272,273,274,275
0,1,0.544070,0.657863,0.611239,0.545413,0.532156,0.593013,0.595280,0.538277,0.563429,...,0.588226,0.577886,0.598069,0.583695,0.602877,0.554263,0.514147,0.603773,0.596331,0.583224
1,2,0.766430,0.624632,0.742247,0.668222,0.766118,0.730685,0.655109,0.729330,0.723651,...,0.686194,0.684996,0.654007,0.689981,0.641813,0.672799,0.616731,0.722182,0.667856,0.724446
2,4,-2.045012,-2.091677,-2.077637,-2.033517,-1.990173,-2.057709,-2.012843,-2.050970,-2.055316,...,0.555466,0.524429,0.485412,0.550532,0.597550,0.606428,0.522934,0.524287,0.547425,0.570562
3,3,-1.705022,-1.739124,-1.725659,-1.801718,-1.742543,-1.760366,-1.691572,-1.687520,-1.761512,...,0.649280,0.640694,0.625991,0.616215,0.616879,0.656518,0.595992,0.601644,0.656164,0.582259
4,1,0.541372,0.571908,0.562147,0.520951,0.527494,0.604043,0.540521,0.580383,0.500582,...,0.586000,0.626472,0.609616,0.554285,0.539465,0.533515,0.557752,0.507825,0.513768,0.528132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,0.606528,0.625706,0.633044,0.621388,0.609732,0.568360,0.615106,0.627838,0.611740,...,0.572225,0.658939,0.557588,0.538450,0.546571,0.554693,0.569671,0.584649,0.633834,0.558586
96,2,0.747806,0.762968,0.730123,0.680653,0.771788,0.665610,0.737680,0.762790,0.725818,...,0.751983,0.642603,0.781384,0.764494,0.741093,0.661910,0.685916,0.716611,0.678644,0.724275
97,4,-1.265726,-1.238093,-1.256923,-1.264015,-1.254037,-1.224892,-1.281235,-1.261939,-1.284487,...,0.923418,0.829264,0.875439,0.870189,0.825957,0.844655,0.845533,0.902312,0.873167,0.845766
98,1,0.674236,0.699501,0.724766,0.736954,0.678820,0.667963,0.666761,0.629702,0.618875,...,0.631834,0.630219,0.643520,0.604948,0.612756,0.605087,0.594663,0.680926,0.612721,0.650197
99,2,0.768163,0.716779,0.760637,0.776758,0.783696,0.790634,0.825192,0.696791,0.762911,...,0.750801,0.759026,0.703826,0.745287,0.762516,0.780627,0.740593,0.767407,0.755615,0.679058

In [28]:
df_1 = df.sort_values(by = [0])

In [29]:
df_1

,0,1,2,3,4,5,6,7,8,9,...,266,267,268,269,270,271,272,273,274,275
0,1,0.544070,0.657863,0.611239,0.545413,0.532156,0.593013,0.595280,0.538277,0.563429,...,0.588226,0.577886,0.598069,0.583695,0.602877,0.554263,0.514147,0.603773,0.596331,0.583224
35,1,0.578414,0.564529,0.621712,0.615501,0.568938,0.590108,0.611278,0.606414,0.662229,...,0.618024,0.582313,0.615947,0.514177,0.565427,0.608845,0.619287,0.616195,0.574924,0.595827
39,1,0.610521,0.621260,0.694262,0.546820,0.579827,0.576833,0.623971,0.549951,0.589048,...,0.619005,0.620541,0.591554,0.593210,0.636987,0.558369,0.593279,0.604549,0.636853,0.622172
45,1,0.502552,0.598754,0.603983,0.544759,0.645436,0.607110,0.584153,0.626348,0.556643,...,0.561244,0.554111,0.543664,0.565976,0.613606,0.599514,0.484127,0.573103,0.589664,0.549785
98,1,0.674236,0.699501,0.724766,0.736954,0.678820,0.667963,0.666761,0.629702,0.618875,...,0.631834,0.630219,0.643520,0.604948,0.612756,0.605087,0.594663,0.680926,0.612721,0.650197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,4,-1.904420,-1.927255,-1.890280,-1.900769,-1.897393,-1.928063,-1.916945,-1.954691,-1.914794,...,0.619676,0.540935,0.572456,0.602884,0.594657,0.592506,0.543837,0.529457,0.609561,0.586370
46,4,-1.665489,-1.647157,-1.587652,-1.653690,-1.611148,-1.598953,-1.625933,-1.622408,-1.602705,...,0.678327,0.647362,0.684946,0.645228,0.687207,0.698321,0.644367,0.700318,0.623251,0.652755
75,4,-1.499155,-1.479791,-1.440565,-1.473746,-1.518472,-1.523205,-1.461763,-1.507300,-1.486842,...,0.746073,0.739075,0.740359,0.690094,0.728535,0.723025,0.728732,0.706519,0.724346,0.710523
21,4,-1.528701,-1.489130,-1.494410,-1.524356,-1.498376,-1.447686,-1.546160,-1.545736,-1.482808,...,0.746798,0.703390,0.719697,0.730584,0.733897,0.709781,0.736965,0.758608,0.684470,0.703240
69,4,-2.020488,-2.038183,-2.031425,-2.088887,-2.037234,-2.056556,-2.146249,-2.078076,-2.062645,...,0.547296,0.543265,0.523343,0.516688,0.510032,0.515707,0.530190,0.580528,0.558666,0.574958

In [30]:
df_2 = df_1.drop([0], axis=1)

In [31]:
df_2

,1,2,3,4,5,6,7,8,9,10,...,266,267,268,269,270,271,272,273,274,275
0,0.544070,0.657863,0.611239,0.545413,0.532156,0.593013,0.595280,0.538277,0.563429,0.595956,...,0.588226,0.577886,0.598069,0.583695,0.602877,0.554263,0.514147,0.603773,0.596331,0.583224
35,0.578414,0.564529,0.621712,0.615501,0.568938,0.590108,0.611278,0.606414,0.662229,0.638254,...,0.618024,0.582313,0.615947,0.514177,0.565427,0.608845,0.619287,0.616195,0.574924,0.595827
39,0.610521,0.621260,0.694262,0.546820,0.579827,0.576833,0.623971,0.549951,0.589048,0.632450,...,0.619005,0.620541,0.591554,0.593210,0.636987,0.558369,0.593279,0.604549,0.636853,0.622172
45,0.502552,0.598754,0.603983,0.544759,0.645436,0.607110,0.584153,0.626348,0.556643,0.552215,...,0.561244,0.554111,0.543664,0.565976,0.613606,0.599514,0.484127,0.573103,0.589664,0.549785
98,0.674236,0.699501,0.724766,0.736954,0.678820,0.667963,0.666761,0.629702,0.618875,0.671192,...,0.631834,0.630219,0.643520,0.604948,0.612756,0.605087,0.594663,0.680926,0.612721,0.650197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,-1.904420,-1.927255,-1.890280,-1.900769,-1.897393,-1.928063,-1.916945,-1.954691,-1.914794,-1.896685,...,0.619676,0.540935,0.572456,0.602884,0.594657,0.592506,0.543837,0.529457,0.609561,0.586370
46,-1.665489,-1.647157,-1.587652,-1.653690,-1.611148,-1.598953,-1.625933,-1.622408,-1.602705,-1.602250,...,0.678327,0.647362,0.684946,0.645228,0.687207,0.698321,0.644367,0.700318,0.623251,0.652755
75,-1.499155,-1.479791,-1.440565,-1.473746,-1.518472,-1.523205,-1.461763,-1.507300,-1.486842,-1.472481,...,0.746073,0.739075,0.740359,0.690094,0.728535,0.723025,0.728732,0.706519,0.724346,0.710523
21,-1.528701,-1.489130,-1.494410,-1.524356,-1.498376,-1.447686,-1.546160,-1.545736,-1.482808,-1.500363,...,0.746798,0.703390,0.719697,0.730584,0.733897,0.709781,0.736965,0.758608,0.684470,0.703240
69,-2.020488,-2.038183,-2.031425,-2.088887,-2.037234,-2.056556,-2.146249,-2.078076,-2.062645,-2.040551,...,0.547296,0.543265,0.523343,0.516688,0.510032,0.515707,0.530190,0.580528,0.558666,0.574958

In [32]:
df_3 = df_2.reset_index(drop=True)
df = df_3
df

,1,2,3,4,5,6,7,8,9,10,...,266,267,268,269,270,271,272,273,274,275
0,0.544070,0.657863,0.611239,0.545413,0.532156,0.593013,0.595280,0.538277,0.563429,0.595956,...,0.588226,0.577886,0.598069,0.583695,0.602877,0.554263,0.514147,0.603773,0.596331,0.583224
1,0.578414,0.564529,0.621712,0.615501,0.568938,0.590108,0.611278,0.606414,0.662229,0.638254,...,0.618024,0.582313,0.615947,0.514177,0.565427,0.608845,0.619287,0.616195,0.574924,0.595827
2,0.610521,0.621260,0.694262,0.546820,0.579827,0.576833,0.623971,0.549951,0.589048,0.632450,...,0.619005,0.620541,0.591554,0.593210,0.636987,0.558369,0.593279,0.604549,0.636853,0.622172
3,0.502552,0.598754,0.603983,0.544759,0.645436,0.607110,0.584153,0.626348,0.556643,0.552215,...,0.561244,0.554111,0.543664,0.565976,0.613606,0.599514,0.484127,0.573103,0.589664,0.549785
4,0.674236,0.699501,0.724766,0.736954,0.678820,0.667963,0.666761,0.629702,0.618875,0.671192,...,0.631834,0.630219,0.643520,0.604948,0.612756,0.605087,0.594663,0.680926,0.612721,0.650197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,-1.904420,-1.927255,-1.890280,-1.900769,-1.897393,-1.928063,-1.916945,-1.954691,-1.914794,-1.896685,...,0.619676,0.540935,0.572456,0.602884,0.594657,0.592506,0.543837,0.529457,0.609561,0.586370
96,-1.665489,-1.647157,-1.587652,-1.653690,-1.611148,-1.598953,-1.625933,-1.622408,-1.602705,-1.602250,...,0.678327,0.647362,0.684946,0.645228,0.687207,0.698321,0.644367,0.700318,0.623251,0.652755
97,-1.499155,-1.479791,-1.440565,-1.473746,-1.518472,-1.523205,-1.461763,-1.507300,-1.486842,-1.472481,...,0.746073,0.739075,0.740359,0.690094,0.728535,0.723025,0.728732,0.706519,0.724346,0.710523
98,-1.528701,-1.489130,-1.494410,-1.524356,-1.498376,-1.447686,-1.546160,-1.545736,-1.482808,-1.500363,...,0.746798,0.703390,0.719697,0.730584,0.733897,0.709781,0.736965,0.758608,0.684470,0.703240
99,-2.020488,-2.038183,-2.031425,-2.088887,-2.037234,-2.056556,-2.146249,-2.078076,-2.062645,-2.040551,...,0.547296,0.543265,0.523343,0.516688,0.510032,0.515707,0.530190,0.580528,0.558666,0.574958

In [33]:
X_1 = df.to_numpy(dtype = None, copy = False)

In [34]:
opt_cluster_1 = []
dist_mat = calculate_dist_mat(X_1)
k_max = 20
b = np.zeros((k_max,k_max))
hier1 = [[i] for i in range(len(dist_mat))]
opt_cluster_1 += [clustering(X_1,dist_mat, hier1,[],20,[],b)]

In [35]:
opt_cluster_1

[2]